"""initial WGDSS schema

Revision ID: 87c46bdfdad4
Revises: 
Create Date: 2026-06-27 15:55:12.173189
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c46bdfdad4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_import_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_archive', sa.String(length=255), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('import_status', sa.String(length=32), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calibration_import_runs_imported_at', 'calibration_import_runs', ['imported_at'], unique=False)
    op.create_index('idx_calibration_import_runs_source_archive', 'calibration_import_runs', ['source_archive'], unique=False)
    op.create_table('calibration_scenario_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_key', sa.String(length=32), nullable=False),
    sa.Column('scenario_label', sa.String(length=128), nullable=False),
    sa.Column('operating_regime', sa.String(length=64), nullable=False),
    sa.Column('source_archive', sa.String(length=255), nullable=False),
    sa.Column('source_workbook', sa.String(length=255), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('hour_of_day', sa.Integer(), nullable=False),
    sa.Column('demand_mw', sa.Float(), nullable=False),
    sa.Column('spin_mw', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calibration_scenario_profiles_hour', 'calibration_scenario_profiles', ['scenario_key', 'hour_of_day'], unique=False)
    op.create_index('idx_calibration_scenario_profiles_scenario', 'calibration_scenario_profiles', ['scenario_key'], unique=False)
    op.create_index('idx_calibration_scenario_profiles_source', 'calibration_scenario_profiles', ['source_archive', 'source_workbook'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Integer(), nullable=False),
    sa.Column('rainfall_mm_hr', sa.Float(), nullable=False),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=False),
    sa.Column('wind_speed_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction_deg', sa.Integer(), nullable=False),
    sa.Column('precipitation_probability_percent', sa.Integer(), nullable=False),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=False),
    sa.Column('heat_index_c', sa.Float(), nullable=False),
    sa.Column('rain_severity', sa.String(length=25), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_timestamp_provider', 'forecasts', ['forecast_timestamp', 'provider_name'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_timestamp'), 'forecasts', ['forecast_timestamp'], unique=False)
    op.create_table('generation_units',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('station_name', sa.String(length=50), nullable=False),
    sa.Column('unit_name', sa.String(length=50), nullable=False),
    sa.Column('fuel_type', sa.String(length=25), nullable=False),
    sa.Column('available_capacity_mw', sa.Float(), nullable=False),
    sa.Column('current_output_mw', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=25), nullable=False),
    sa.Column('is_dispatchable', sa.Boolean(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_generation_status', 'generation_units', ['status'], unique=False)
    op.create_index('idx_station_unit', 'generation_units', ['station_name', 'unit_name'], unique=False)
    op.create_table('grid_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_demand_mw', sa.Float(), nullable=False),
    sa.Column('current_generation_mw', sa.Float(), nullable=False),
    sa.Column('total_available_capacity_mw', sa.Float(), nullable=False),
    sa.Column('reserve_margin_percent', sa.Float(), nullable=False),
    sa.Column('grid_status', sa.String(length=25), nullable=False),
    sa.Column('demand_period', sa.String(length=25), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_grid_data_provider', 'grid_data', ['source_provider'], unique=False)
    op.create_index('idx_grid_data_timestamp', 'grid_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_grid_data_timestamp'), 'grid_data', ['timestamp'], unique=False)
    op.create_table('historical_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analysis_name', sa.String(length=150), nullable=False),
    sa.Column('analysis_period', sa.String(length=75), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_historical_analysis_created_at', 'historical_analysis', ['created_at'], unique=False)
    op.create_index('idx_historical_analysis_name', 'historical_analysis', ['analysis_name'], unique=False)
    op.create_table('probability_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('probability_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('forecast_demand_30m', sa.Float(), nullable=False),
    sa.Column('forecast_demand_60m', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=64), nullable=False),
    sa.Column('factors', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_probability_results_created_at', 'probability_results', ['created_at'], unique=False)
    op.create_index('idx_probability_results_risk_level', 'probability_results', ['risk_level'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('probability_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('forecast_demand_30m', sa.Float(), nullable=False),
    sa.Column('forecast_demand_60m', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=25), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('factors', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendation_created_at', 'recommendations', ['created_at'], unique=False)
    op.create_index('idx_recommendation_type', 'recommendations', ['recommendation'], unique=False)
    op.create_table('scada_temperature_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_key', sa.String(length=32), nullable=False),
    sa.Column('source_archive', sa.String(length=255), nullable=False),
    sa.Column('source_workbook', sa.String(length=255), nullable=False),
    sa.Column('source_sheet', sa.String(length=255), nullable=False),
    sa.Column('measurement_name', sa.String(length=255), nullable=False),
    sa.Column('pen_index', sa.Integer(), nullable=False),
    sa.Column('sample_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_value_c', sa.Float(), nullable=False),
    sa.Column('max_value_c', sa.Float(), nullable=False),
    sa.Column('avg_value_c', sa.Float(), nullable=False),
    sa.Column('quality_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_scada_temperature_samples_quality', 'scada_temperature_samples', ['quality_status'], unique=False)
    op.create_index('idx_scada_temperature_samples_scenario', 'scada_temperature_samples', ['scenario_key'], unique=False)
    op.create_index('idx_scada_temperature_samples_source', 'scada_temperature_samples', ['source_archive', 'source_workbook'], unique=False)
    op.create_index(op.f('ix_scada_temperature_samples_sample_timestamp'), 'scada_temperature_samples', ['sample_timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('humidity_percent', sa.Float(), nullable=False),
    sa.Column('wind_speed_kph', sa.Float(), nullable=False),
    sa.Column('wind_direction_deg', sa.Float(), nullable=True),
    sa.Column('pressure_hpa', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('rainfall_mm_hr', sa.Float(), nullable=False),
    sa.Column('cloud_cover_percent', sa.Float(), nullable=False),
    sa.Column('weather_condition', sa.String(length=100), nullable=False),
    sa.Column('heat_index_c', sa.Float(), nullable=False),
    sa.Column('rain_severity', sa.String(length=25), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_provider_created_at', 'weather_observations', ['provider_name', 'created_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_timestamp'), 'weather_observations', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_timestamp'), table_name='weather_observations')
    op.drop_index('idx_provider_created_at', table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scada_temperature_samples_sample_timestamp'), table_name='scada_temperature_samples')
    op.drop_index('idx_scada_temperature_samples_source', table_name='scada_temperature_samples')
    op.drop_index('idx_scada_temperature_samples_scenario', table_name='scada_temperature_samples')
    op.drop_index('idx_scada_temperature_samples_quality', table_name='scada_temperature_samples')
    op.drop_table('scada_temperature_samples')
    op.drop_index('idx_recommendation_type', table_name='recommendations')
    op.drop_index('idx_recommendation_created_at', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index('idx_probability_results_risk_level', table_name='probability_results')
    op.drop_index('idx_probability_results_created_at', table_name='probability_results')
    op.drop_table('probability_results')
    op.drop_index('idx_historical_analysis_name', table_name='historical_analysis')
    op.drop_index('idx_historical_analysis_created_at', table_name='historical_analysis')
    op.drop_table('historical_analysis')
    op.drop_index(op.f('ix_grid_data_timestamp'), table_name='grid_data')
    op.drop_index('idx_grid_data_timestamp', table_name='grid_data')
    op.drop_index('idx_grid_data_provider', table_name='grid_data')
    op.drop_table('grid_data')
    op.drop_index('idx_station_unit', table_name='generation_units')
    op.drop_index('idx_generation_status', table_name='generation_units')
    op.drop_table('generation_units')
    op.drop_index(op.f('ix_forecasts_forecast_timestamp'), table_name='forecasts')
    op.drop_index('idx_forecast_timestamp_provider', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index('idx_calibration_scenario_profiles_source', table_name='calibration_scenario_profiles')
    op.drop_index('idx_calibration_scenario_profiles_scenario', table_name='calibration_scenario_profiles')
    op.drop_index('idx_calibration_scenario_profiles_hour', table_name='calibration_scenario_profiles')
    op.drop_table('calibration_scenario_profiles')
    op.drop_index('idx_calibration_import_runs_source_archive', table_name='calibration_import_runs')
    op.drop_index('idx_calibration_import_runs_imported_at', table_name='calibration_import_runs')
    op.drop_table('calibration_import_runs')
    # ### end Alembic commands ###
