import type { DashboardSnapshot } from "../types/dashboard";

export const dashboardFixture: DashboardSnapshot = {
  weather: {
    timestamp: "2026-06-27T12:00:00-04:00",
    temperature_c: 30,
    humidity_percent: 75,
    rainfall_mm_hr: 0.5,
    cloud_cover_percent: 45,
    wind_speed_kmh: 14,
    weather_condition: "Partly cloudy",
    heat_index_c: 34,
    rain_severity: "LIGHT",
    provider_name: "Open-Meteo",
  },
  grid: {
    timestamp: "2026-06-27T12:00:00-04:00",
    current_demand_mw: 950,
    current_generation_mw: 960,
    total_available_capacity_mw: 1200,
    reserve_margin_percent: 26.3,
    grid_status: "NORMAL",
    demand_period: "AFTERNOON",
    source_provider: "MockGridProvider",
    generation_units: [],
  },
  forecast: {
    items: Array.from({ length: 6 }, (_, index) => ({
      forecast_timestamp: `2026-06-27T${13 + index}:00:00-04:00`,
      temperature_c: 30 + index / 10,
      humidity_percent: 74,
      rainfall_mm_hr: 0.2,
      cloud_cover_percent: 50,
      wind_speed_kmh: 15,
      weather_condition: "Partly cloudy",
      heat_index_c: 34,
      precipitation_probability_percent: 20,
      confidence_score: 0.9,
      rain_severity: "LIGHT",
      provider_name: "Consensus (Open-Meteo + MET Norway)",
      source_count: 3,
      source_names: ["Open-Meteo Best Match", "MET Norway", "Open-Meteo NOAA GFS"],
      temperature_spread_c: 0.4,
      cloud_cover_spread_percent: 12,
    })),
  },
  probability: {
    probability_score: 0.42,
    risk_level: "LOW",
    forecast_demand_30m: 970,
    forecast_demand_60m: 985,
    factors: ["Conditions remain stable"],
    reason: "Conditions remain stable",
  },
  recommendation: {
    probability_score: 0.42,
    risk_level: "LOW",
    forecast_demand_30m: 970,
    forecast_demand_60m: 985,
    factors: ["Conditions remain stable"],
    reason: "Conditions remain stable",
    recommendation: "NO ACTION REQUIRED",
  },
  calibration: {
    selected_scenario_key: "typical",
    selected_scenario_label: "Typical Day",
    selected_temperature_c: 30,
    selection_reason: "Typical profile is the closest match",
    selection_confidence: 0.8,
    scenario_scores: { hot: 0.5, typical: 0.8, rainy: 0.3 },
    scenarios: [],
  },
  data_quality: {
    overall_status: "GOOD",
    weather_status: "LIVE",
    grid_status: "SIMULATED",
    calibration_status: "CALIBRATED",
    weather_source: "Open-Meteo",
    grid_source: "MockGridProvider",
    observed_at: "2026-06-27T12:00:00-04:00",
    age_seconds: 30,
    is_stale: false,
    fallback_used: false,
    notes: [],
  },
  demand_forecast: {
    horizons: [
      {
        horizon_hours: 1,
        forecast_timestamp: "2026-06-27T13:00:00-04:00",
        forecast_demand_mw: 990,
        forecast_uncertainty_mw: 18,
        model_name: "persistence",
        model_version: "demand-forecast-v1.3",
        baseline_name: "persistence",
        baseline_forecast_mw: 985,
        quality_status: "BASELINE_ACTIVE",
      },
    ],
  },
  model_status: {
    active_model: "persistence",
    model_version: "demand-forecast-v1.3",
    mode: "BASELINE_ACTIVE",
    trained_through: "2026-06-27T13:00:00-04:00",
    metrics: {
      mae: 10,
      rmse: 12,
      mape: 1.2,
      residual_std: 18,
    },
    baseline_comparison: {
      best_baseline: "persistence",
      ml_beats_baseline: false,
    },
  },
  scada_status: {
    source: "scada.csv",
    latest_snapshot: "2026-06-27T12:00:00-04:00",
    quality_status: "GOOD",
    missing_fields: "",
  },
};
