import type { DashboardSnapshot } from "../types/dashboard";

export const dashboardFixture: DashboardSnapshot = {
  weather: {
    timestamp: "2026-06-27T12:00:00-04:00",
    temperature_c: 30,
    humidity_percent: 75,
    rainfall_mm_hr: 0.5,
    cloud_cover_percent: 45,
    wind_speed_kmh: 14,
    weather_condition: "Partly cloudy",
    heat_index_c: 34,
    rain_severity: "LIGHT",
    provider_name: "Open-Meteo",
  },
  grid: {
    timestamp: "2026-06-27T12:00:00-04:00",
    current_demand_mw: 950,
    current_generation_mw: 960,
    total_available_capacity_mw: 1200,
    reserve_margin_percent: 26.3,
    grid_status: "NORMAL",
    demand_period: "AFTERNOON",
    source_provider: "MockGridProvider",
    generation_units: [],
  },
  forecast: {
    items: Array.from({ length: 6 }, (_, index) => ({
      forecast_timestamp: `2026-06-27T${13 + index}:00:00-04:00`,
      temperature_c: 30 + index / 10,
      humidity_percent: 74,
      rainfall_mm_hr: 0.2,
      cloud_cover_percent: 50,
      wind_speed_kmh: 15,
      weather_condition: "Partly cloudy",
      heat_index_c: 34,
      precipitation_probability_percent: 20,
      confidence_score: 0.9,
      rain_severity: "LIGHT",
      provider_name: "Consensus (Open-Meteo + MET Norway)",
      source_count: 3,
      source_names: ["Open-Meteo Best Match", "MET Norway", "Open-Meteo NOAA GFS"],
      temperature_spread_c: 0.4,
      cloud_cover_spread_percent: 12,
    })),
  },
  probability: {
    probability_score: 0.42,
    risk_level: "LOW",
    forecast_demand_30m: 970,
    forecast_demand_60m: 985,
    factors: ["Conditions remain stable"],
    reason: "Conditions remain stable",
  },
  recommendation: {
    probability_score: 0.42,
    risk_level: "LOW",
    forecast_demand_30m: 970,
    forecast_demand_60m: 985,
    factors: ["Conditions remain stable"],
    reason: "Conditions remain stable",
    recommendation: "NO ACTION REQUIRED",
  },
  calibration: {
    selected_scenario_key: "typical",
    selected_scenario_label: "Typical Day",
    selected_temperature_c: 30,
    selection_reason: "Typical profile is the closest match",
    selection_confidence: 0.8,
    scenario_scores: { hot: 0.5, typical: 0.8, rainy: 0.3 },
    scenarios: [],
  },
  data_quality: {
    overall_status: "GOOD",
    weather_status: "LIVE",
    grid_status: "SIMULATED",
    calibration_status: "CALIBRATED",
    weather_source: "Open-Meteo",
    grid_source: "MockGridProvider",
    observed_at: "2026-06-27T12:00:00-04:00",
    age_seconds: 30,
    is_stale: false,
    fallback_used: false,
    notes: [],
  },
  demand_forecast: {
    horizons: [
      {
        horizon_hours: 1,
        forecast_timestamp: "2026-06-27T13:00:00-04:00",
        forecast_demand_mw: 990,
        forecast_uncertainty_mw: 18,
        model_name: "persistence",
        model_version: "demand-forecast-v1.3",
        baseline_name: "persistence",
        baseline_forecast_mw: 985,
        quality_status: "BASELINE_ACTIVE",
      },
    ],
  },
  model_status: {
    active_model: "persistence",
    model_version: "demand-forecast-v1.3",
    mode: "BASELINE_ACTIVE",
    trained_through: "2026-06-27T13:00:00-04:00",
    metrics: {
      mae: 10,
      rmse: 12,
      mape: 1.2,
      residual_std: 18,
    },
    baseline_comparison: {
      best_baseline: "persistence",
      ml_beats_baseline: false,
    },
  },
  scada_status: {
    source: "scada.csv",
    latest_snapshot: "2026-06-27T12:00:00-04:00",
    quality_status: "GOOD",
    missing_fields: "",
  },
};

export const replayDashboardFixture: DashboardSnapshot = {
  ...dashboardFixture,
  weather: {
    ...dashboardFixture.weather,
    timestamp: "2025-06-01T08:00:00-04:00",
    provider_name: "Simulated Live · Historical Weather Replay",
  },
  grid: {
    ...dashboardFixture.grid,
    timestamp: "2025-06-01T08:00:00-04:00",
    source_provider: "SimulatedLiveScadaReplay",
  },
  replay: {
    status: {
      mode: "SIMULATED_LIVE",
      dataset_label: "2025 hourly SCADA + weather demonstration",
      dataset_start: "2025-01-01T00:00:00-04:00",
      dataset_end: "2025-12-31T23:00:00-04:00",
      replay_start: "2025-06-01T00:00:00-04:00",
      replay_end: "2025-06-30T23:00:00-04:00",
      cursor_at: "2025-06-01T08:00:00-04:00",
      is_playing: false,
      step_minutes: 60,
      speed_multiplier: 600,
      progress_percent: 1.1,
      revealed_records: 9,
      total_replay_records: 720,
      source: "WGDSS 12-Month Synthetic SCADA/Weather Demonstration",
    },
    operational_history: [],
    full_day_load_forecast: Array.from({ length: 24 }, (_, hour) => ({
      timestamp: `2025-06-01T${String(hour).padStart(2, "0")}:00:00-04:00`,
      forecast_demand_mw: 800 + hour * 10,
      historical_average_mw: 790 + hour * 9,
      actual_demand_mw: hour <= 8 ? 795 + hour * 10 : null,
      uncertainty_mw: 20,
    })),
    monthly_history: Array.from({ length: 12 }, (_, index) => ({
      month: new Intl.DateTimeFormat("en", { month: "short", timeZone: "UTC" }).format(new Date(Date.UTC(2025, index, 1))),
      average_demand_mw: 880 + index * 4,
      peak_demand_mw: 1220 + index * 5,
      average_temperature_c: 27 + index / 10,
      rainfall_total_mm: 40 + index * 8,
      data_phase: index === 5 ? "REPLAY_SOURCE" as const : "HISTORICAL" as const,
    })),
    summary: {
      historical_months: 11,
      historical_record_count: 8040,
      historical_average_demand_mw: 910,
      historical_peak_demand_mw: 1320,
      replay_month_label: "June 2025",
      current_day_peak_forecast_mw: 1030,
    },
  },
};
